baseurl = "/"
languageCode = "en-us"
Title = "Kirti Bhardwaj"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Belongs to Kirti Bhardwaj"
theme = "hugo_theme_pickles"
pygmentsStyle = "native"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "kirtib"
  github = "LostWarrior"
  linkedin = "kirtib/"
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  author = "Kirti Bhardwaj"
  contact = "mailto:kirti.sbhardwaj@gmail.com)"
  bio = "A web developer,data visualizer based out of Bangalore, India."

[[menu.main]]
    name = "Blog"
    url = "/posts/installing-postgres-linux-mint/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 0
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 10
  [[related.indices]]
  name  = "tags"
  weight = 0
  [[related.indices]]
  name  = "date"
  weight = 5
  pattern = "2017"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"